name: Swift nightly build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-nightly
  cancel-in-progress: true

env:
  AWS_SECRET_ACCESS_KEY: "MYSECRETACCESSKEY"
  AWS_ACCESS_KEY_ID: "MYACCESSKEYID"
  LOCALSTACK_ENDPOINT: "http://localstack:4566"

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image: ['nightly-focal', 'nightly-jammy', 'nightly-amazonlinux2']
    services:
      localstack:
        image: localstack/localstack
    container:
      image: swiftlang/swift:${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Test
      run: |
        swift test
