name: Validity Check

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-validate
  cancel-in-progress: true
  
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
    - name: run script
      run: ./scripts/validate.sh
